//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalInfoApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LocalInfoApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\n{1}.
        /// </summary>
        internal static string DisplayFormatSportsScoreValues {
            get {
                return ResourceManager.GetString("DisplayFormatSportsScoreValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\n{1:ddd MMM d}{2}.
        /// </summary>
        internal static string DisplayFormatSportsStatusAndDate {
            get {
                return ResourceManager.GetString("DisplayFormatSportsStatusAndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\n{1}.
        /// </summary>
        internal static string DisplayFormatSportsTeams {
            get {
                return ResourceManager.GetString("DisplayFormatSportsTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}\n{1}: {2}\n{3:0.00} {4}\n{5}{6:0.00} ({7:0.00}%) {8}.
        /// </summary>
        internal static string DisplayFormatStocks {
            get {
                return ResourceManager.GetString("DisplayFormatStocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}°.
        /// </summary>
        internal static string DisplayFormatTemp {
            get {
                return ResourceManager.GetString("DisplayFormatTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM-dd h:mm tt.
        /// </summary>
        internal static string DisplayFormatWeatherDateAndTime {
            get {
                return ResourceManager.GetString("DisplayFormatWeatherDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Wind {0} {1} {2}.
        /// </summary>
        internal static string DisplayFormatWeatherWind {
            get {
                return ResourceManager.GetString("DisplayFormatWeatherWind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suncor Energy Inc..
        /// </summary>
        internal static string DisplayStockCompanyName {
            get {
                return ResourceManager.GetString("DisplayStockCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SU.
        /// </summary>
        internal static string DisplayStockCompanySymbol {
            get {
                return ResourceManager.GetString("DisplayStockCompanySymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAD.
        /// </summary>
        internal static string DisplayStockCurrency {
            get {
                return ResourceManager.GetString("DisplayStockCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSE.
        /// </summary>
        internal static string DisplayStockExchangeSymbol {
            get {
                return ResourceManager.GetString("DisplayStockExchangeSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        internal static string DisplayWeatherWindDirectionEast {
            get {
                return ResourceManager.GetString("DisplayWeatherWindDirectionEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        internal static string DisplayWeatherWindDirectionNorth {
            get {
                return ResourceManager.GetString("DisplayWeatherWindDirectionNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE.
        /// </summary>
        internal static string DisplayWeatherWindDirectionNorthEast {
            get {
                return ResourceManager.GetString("DisplayWeatherWindDirectionNorthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NW.
        /// </summary>
        internal static string DisplayWeatherWindDirectionNorthWest {
            get {
                return ResourceManager.GetString("DisplayWeatherWindDirectionNorthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        internal static string DisplayWeatherWindDirectionSouth {
            get {
                return ResourceManager.GetString("DisplayWeatherWindDirectionSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE.
        /// </summary>
        internal static string DisplayWeatherWindDirectionSouthEast {
            get {
                return ResourceManager.GetString("DisplayWeatherWindDirectionSouthEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW.
        /// </summary>
        internal static string DisplayWeatherWindDirectionSouthWest {
            get {
                return ResourceManager.GetString("DisplayWeatherWindDirectionSouthWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        internal static string DisplayWeatherWindDirectionWest {
            get {
                return ResourceManager.GetString("DisplayWeatherWindDirectionWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km/h.
        /// </summary>
        internal static string DisplayWeatherWindMeasurementKPH {
            get {
                return ResourceManager.GetString("DisplayWeatherWindMeasurementKPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mph.
        /// </summary>
        internal static string DisplayWeatherWindMeasurementMPH {
            get {
                return ResourceManager.GetString("DisplayWeatherWindMeasurementMPH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found.
        /// </summary>
        internal static string EndpointResultEmpty {
            get {
                return ResourceManager.GetString("EndpointResultEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred.
        /// </summary>
        internal static string EndpointResultError {
            get {
                return ResourceManager.GetString("EndpointResultError", resourceCulture);
            }
        }
    }
}
