

namespace LocalInfoApp
{
    // generated by Visual Studio to match json data result from stock api / finnhub

    public class JsonStockQuote   // the root object
    {
        public float c { get; set; }
        public float h { get; set; }
        public float l { get; set; }
        public float o { get; set; }
        public float pc { get; set; }
        public int t { get; set; }
    }

}
